version: "3"
services:
  s3-sync:
    image: heycar/s3-sync:0.1.0
    volumes:
        - ./data:/data
    environment:
      - CRON_SCHEDULE=1/1 * * * *
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_S3_BUCKET_URI=s3://my-bucket/
