version: "3"
services:
  s3-sync:
    image: heycar/s3-sync:0.3.0
    volumes:
        - ./data:/data
    environment:
      - NOW='false'
      - CRON_SCHEDULE=1/1 * * * *
      - FROM=s3://foo/bar
      - TO=/data
